version: '2'
services:

  newsblur_web:
    hostname: nb.com
    container_name: newsblur_web
    image: newsblur/newsblur_${NEWSBLUR_BASE:-python3}:latest
    # build: 
    #   context: /srv/newsblur
    #   dockerfile: docker/newsblur_base_image.Dockerfile
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment: 
      - DOCKERBUILD=True
      - RUNWITHMAKEBUILD=${RUNWITHMAKEBUILD?Use the `make` command instead of docker CLI}
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - db_mongo
      - db_postgres
      - db_redis
      - db_elasticsearch
    ulimits:
      nproc: 10000
      nofile:
        soft: 10000
        hard: 10000
    ports:
      - 8000:8000
    # only use gunicorn if the TEST env variable is not "True"
    entrypoint: /bin/sh -c newsblur_web/entrypoint.sh
    volumes: 
      - ${PWD}:/srv/newsblur
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur Web
      - homepage.icon=newsblur.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=Web

  newsblur_node:
    container_name: node
    image: newsblur/newsblur_node:latest
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      - NODE_ENV=docker
      - MONGODB_PORT=29019
    command: node newsblur.js
    restart: unless-stopped
    stop_signal: HUP
    depends_on: 
      - db_mongo
      - db_postgres
      - db_redis
    ports:
      - 8008:8008
    volumes: 
      - ${PWD}/node:/srv
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur Nodeb
      - homepage.icon=node-red.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=Node   
  
  imageproxy:
    container_name: imageproxy
    # image: ghcr.io/willnorris/imageproxy:latest # Enable if you don't need arm64 and want the original imageproxy
    image: yusukeito/imageproxy:v0.11.2 # Enable if you want arm64 
    user: "${CURRENT_UID}:${CURRENT_GID}"
    entrypoint: /app/imageproxy -addr 0.0.0.0:8088 -cache /tmp/imageproxy -verbose
    restart: unless-stopped
    ports:
      - 8088:8088
    volumes:
      - /mnt/usbssd1/data/NewsBlur/tmp:/tmp/imageproxy
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur imageproxy
      - homepage.icon=proxmox.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=Imageproxy
  
  nginx:
    container_name: nginx
    image: nginx:1.19.6
    restart: unless-stopped
    ports:
      - 81:81
    depends_on:
      - newsblur_web
      - newsblur_node
      - db_postgres
      - db_redis
      - db_mongo
      - db_elasticsearch
    environment: 
      - DOCKERBUILD=True
    volumes:
      - ./docker/nginx/nginx.local.conf:/etc/nginx/conf.d/nginx.conf
      - ${PWD}:/srv/newsblur
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur nginx
      - homepage.icon=nginx.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=Nginx

  db_postgres:
    container_name: db_postgres
    image: postgres:13.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=newsblur
      - POSTGRES_PASSWORD=newsblur
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U newsblur"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - 5434:5432
    volumes:
      - /mnt/usbssd1/data/NewsBlur/postgres:/var/lib/postgresql/data
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur db_postgres
      - homepage.icon=postgres.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=db_postgres

  db_redis:
    container_name: db_redis
    image: redis:latest
    ports:
      - 6579:6579
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - ./docker/redis/redis_server.conf:/usr/local/etc/redis/redis_replica.conf
      - /mnt/usbssd1/data/NewsBlur/redis:/data
    command: redis-server /etc/redis/redis.conf --port 6579
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur db_redis
      - homepage.icon=redis.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=db_redis

  db_elasticsearch:
    container_name: db_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    mem_limit: 1073741824
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /mnt/usbssd1/data/NewsBlur/elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur db_elasticsearch
      - homepage.icon=elasticsearch.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=db_elasticsearch

  dejavu:
    container_name: dejavu
    image: appbaseio/dejavu:3.6.0
    restart: unless-stopped
    ports:
      - 1358:1358
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur dejavu
      - homepage.icon=dc-os.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=dejavu

  db_mongo:
    container_name: db_mongo
    image: mongo:4.0
    user: mongodb
    restart: unless-stopped
    ports:
      - 29019:29019
    command: mongod --port 29019
    volumes:
      - /mnt/usbssd1/data/NewsBlur/db_mongo:/data/db
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur db_mongo
      - homepage.icon=mongodb.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=db_mongo

  task_celery:
    container_name: task_celery
    image: newsblur/newsblur_python3
    user: "${CURRENT_UID}:${CURRENT_GID}"
    command: "celery worker -A newsblur_web -B --loglevel=INFO"
    restart: unless-stopped
    volumes:
      - ${PWD}:/srv/newsblur
    environment: 
      - DOCKERBUILD=True
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur task_celery
      - homepage.icon=taskcafe.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=task_celery

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: unless-stopped
    depends_on: 
      - nginx
      - newsblur_web
      - newsblur_node
      - imageproxy
      - db_redis
      - db_postgres
      - db_elasticsearch
      - db_mongo
    ports:
      - 8001:80
      - 4431:443
      - 1936:1936
    volumes:
      - ./docker/haproxy/haproxy.docker-compose.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}:/srv/newsblur
    labels:
      - homepage.group=RSS
      - homepage.name=NewsBlur haproxy
      - homepage.icon=haproxy.png
      - homepage.href=https://nb.vlakor.ru
      - homepage.description=haproxy
